name: Build ZMK firmware
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main


  dump-config:
    name: Dump final .config (right shield)
    runs-on: ubuntu-latest
    container: ghcr.io/zmkfirmware/zmk-dev:stable
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: West init & update
        run: |
          west init -l .
          west update
          west zephyr-export

      - name: Configure & build (right / central)
        run: |
          west build -s zmk/app -d build-right -b akdk_bt1 -S studio-rpc-usb-uart -- \
            -DZMK_CONFIG=$GITHUB_WORKSPACE/config \
            -DSHIELD=surround1x0_akdk_right

      - name: Upload .config artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: config-right
          path: build-right/zephyr/.config
          if-no-files-found: error
