name: Build ZMK firmware
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main

  dump-config:
    needs: build
    runs-on: ubuntu-latest
    container: zmkfirmware/zmk-dev-arm:3.5-branch
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare git & show west
        run: |
          set -xe
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          west --version || true
          git --version || true
          ls -la

      - name: West init & update
        run: |
          set -xe
          # カレントディレクトリ(=$GITHUB_WORKSPACE)を west ワークスペースにする
          west init -m https://github.com/zmkfirmware/zmk .
          # Git の ownership 警告を抑止（manifest/zmk も含めて許可）
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --global --add safe.directory "$GITHUB_WORKSPACE/zmk"
          git config --global --add safe.directory "$GITHUB_WORKSPACE/zephyr"
          west update
          west zephyr-export
          # デバッグ用
          west list || true
          ls -la .west || true
          ls -la zmk || true
          ls -la zephyr || true

      - name: Build right (generate .config)
        run: |
          set -xe
          ls -la
          west build -s zmk/app -d build-right -b akdk_bt1 -S studio-rpc-usb-uart -- \
            -DZMK_CONFIG=$GITHUB_WORKSPACE/config \
            -DSHIELD=surround1x0_akdk_right \
            -DZMK_EXTRA_MODULES=$GITHUB_WORKSPACE \
            -DCONFIG_ZMK_STUDIO=y
          ls -la build-right/zephyr || true

      - name: Upload .config and CMakeCache
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: config-right
          path: |
            build-right/zephyr/.config
            build-right/CMakeCache.txt
          if-no-files-found: error
